# Site settings
title: Your awesome title
email: karci.ada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /adakarci.github.io # the subpath of your site, e.g. /blog/
url: "http://adakarci.github.io" # the base hostname & protocol for your site

github_username:  adakarci

# Build settings
markdown: kramdown
