# Site settings
title: Just Blog
email: karci.ada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  adakarci

# Build settings
markdown: kramdown
